version: '3.3'

services:
  foodgram_web:
    image: yadovj/foodgram:latest
    expose:
      - 80
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    env_file:
      - ./.env
    container_name: foodgram_web
  
  frontend:
    depends_on:
      - foodgram_web
    image: yadovj/foodgram_front:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    restart: always
    expose:
      - 81
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/usr/share/nginx/html/backend_static/:ro
      - media_value:/usr/share/nginx/html/media/:ro
    depends_on:
      - frontend
    env_file:
      - ./.env
    

volumes:
  static_value:
  media_value:

networks:
  default:
    name: nginx-proxy
    external: true
